# Consensus Simulation

In [1]:
from graph import *

# 1. Graph Construction

In [2]:
V = tuple(range(5))
E = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 0), (1, 0), (2, 1), (3, 2), (4, 3), (0, 4)]
A = np.array([[0, 1, 0, 0, 1],
              [1, 0, 1, 0, 0],
              [0, 1, 0, 1, 0],
              [0, 0, 1, 0, 1],
              [1, 0, 0, 1, 0]])
G_dir = DiGraph(V, E, A)

print(f"Number of nodes: {G_dir.graph.number_of_nodes()}")
print(f"{G_dir.graph.nodes()}")
print(f"Number of edges: {G_dir.graph.number_of_edges()}")
print(f"{G_dir.graph.edges()}")
print(f"Adjacency matrix:\n{G_dir.adj}")

Number of nodes: 5
[0, 1, 2, 3, 4]
Number of edges: 10
[(0, 1), (0, 4), (1, 2), (1, 0), (2, 3), (2, 1), (3, 4), (3, 2), (4, 0), (4, 3)]
Adjacency matrix:
[[0 1 0 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [1 0 0 1 0]]


In [3]:
V = tuple(range(5))
E = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 0)]
G_undir = UnDiGraph(V, E)

print(f"Number of nodes: {G_undir.graph.number_of_nodes()}")
print(f"{G_undir.graph.nodes()}")
print(f"Number of edges: {G_undir.graph.number_of_edges()}")
print(f"{G_undir.graph.edges()}")
print(f"Adjacency matrix:\n{G_undir.adj}")

Number of nodes: 5
[0, 1, 2, 3, 4]
Number of edges: 5
[(0, 1), (0, 4), (1, 2), (2, 3), (3, 4)]
Adjacency matrix:
[[0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]]


# 2. Laplacian Construction

AttributeError: 'Graph' object has no attribute 'in_degree'

# 3. Consensus